#!/bin/sh

set -o pipefail
set -e

. scripts/common.sh

# build Lua script dependencies
./build_deps

# run backend container
sh scripts/run_backend.sh

# build base proxy image
sh scripts/build_proxy_base_image.sh

# build proxy containers and images
for proxy_dir in hosts/proxy/*; do
    [ -d "${proxy_dir}" ] || continue # if not a directory, skip

    proxy_name="$(basename $proxy_dir)"

    sh scripts/run_proxy_container.sh $proxy_name
done

echo "${cyan}Running integration tests:${no_color}"
cd test
# make sure npm packages are installed
npm install
# run tests
npm test

# shut down all containers and remove all images
for proxy_dir in hosts/proxy/*; do
    [ -d "${proxy_dir}" ] || continue # if not a directory, skip

    proxy_name="$(basename $proxy_dir)"

    sh scripts/stop_proxy_container.sh $proxy_name
done

sh scripts/stop_backend.sh
